Repository Marco0198/school_management-, pull requests merged in 2022-06, with the labels that each got.

#24 employee domain class
  src/main/java/ac/za/cput/domain/employee/Employee.java
  src/main/java/ac/za/cput/domain/name/Name.java
Labels: enhancement

#25 domain class for student
  src/main/java/ac/za/cput/domain/employee/Employee.java
  src/main/java/ac/za/cput/domain/student/Student.java
Labels: enhancement

#26 actory class for student
  src/main/java/ac/za/cput/factory/student/StudentFactory.java
  src/main/java/ac/za/cput/helper/StringHelper.java
Labels: enhancement

#27 factory class for employee
  src/main/java/ac/za/cput/factory/employee/EmployeeFactory.java
Labels: enhancement

#28 repository class for student and employee using jpa
  src/main/java/ac/za/cput/repository/IRepository.java
  src/main/java/ac/za/cput/repository/employee/EmployeeRepository.java
  src/main/java/ac/za/cput/repository/student/StudentRepository.java
Labels: enhancement

#29 service implementation for employee and student
  .idea/uiDesigner.xml
  src/main/java/ac/za/cput/service/student/StudentService.java
Labels: enhancement

#38 test case for student service and employee
  src/main/java/ac/za/cput/domain/employee/Employee.java
  src/main/java/ac/za/cput/repository/employee/EmployeeRepository.java
  src/main/java/ac/za/cput/repository/student/StudentRepository.java
  src/main/java/ac/za/cput/service/IService.java
  src/main/java/ac/za/cput/service/employee/IEmployeeService.java
  src/main/java/ac/za/cput/service/employee/impl/EmployeeServiceImpl.java
  src/main/java/ac/za/cput/service/student/StudentService.java
  src/main/java/ac/za/cput/service/student/impl/StudentServiceImpl.java
  src/test/java/ac/za/cput/AppTest.java
  src/test/java/ac/za/cput/factory/employee/EmployeeFactoryTest.java
  src/test/java/ac/za/cput/factory/student/StudentFactoryTest.java
  src/test/java/ac/za/cput/service/employee/impl/EmployeeServiceImplTest.java
  src/test/java/ac/za/cput/service/student/impl/StudentServiceImplTest.java
  target/classes/ac/za/cput/domain/employee/Employee$Builder.class
  target/classes/ac/za/cput/domain/employee/Employee.class
  target/classes/ac/za/cput/domain/name/Name.class
  target/classes/ac/za/cput/domain/student/Student$Builder.class
  target/classes/ac/za/cput/domain/student/Student.class
  target/classes/ac/za/cput/factory/employee/EmployeeFactory.class
  target/classes/ac/za/cput/factory/student/StudentFactory.class
  target/classes/ac/za/cput/helper/StringHelper.class
  target/classes/ac/za/cput/repository/IRepository.class
  target/classes/ac/za/cput/repository/employee/EmployeeRepository.class
  target/classes/ac/za/cput/repository/employee/IEmployeeRepository.class
  target/classes/ac/za/cput/repository/student/IStudentRepository.class
  target/classes/ac/za/cput/repository/student/StudentRepository.class
  target/classes/ac/za/cput/service/IService.class
  target/classes/ac/za/cput/service/employee/IEmployeeService.class
  target/classes/ac/za/cput/service/employee/impl/EmployeeServiceImpl.class
  target/classes/ac/za/cput/service/student/IStudentService.class
  target/classes/ac/za/cput/service/student/StudentService.class
  target/classes/ac/za/cput/service/student/impl/StudentServiceImpl.class
  target/test-classes/ac/za/cput/factory/employee/EmployeeFactoryTest.class
  target/test-classes/ac/za/cput/factory/student/StudentFactoryTest.class
  target/test-classes/ac/za/cput/service/employee/impl/EmployeeServiceImplTest.class
  target/test-classes/ac/za/cput/service/student/impl/StudentServiceImplTest.class
Labels: enhancement

#43 fix services
  src/main/java/ac/za/cput/controller/employee/EmployeeController.java
  src/main/java/ac/za/cput/controller/student/StudentController.java
  src/main/java/ac/za/cput/domain/employee/Employee.java
  src/main/java/ac/za/cput/domain/student/Student.java
  src/main/java/ac/za/cput/factory/employee/EmployeeFactory.java
  src/main/java/ac/za/cput/factory/student/StudentFactory.java
  src/main/java/ac/za/cput/repository/employee/EmployeeRepository.java
  src/main/java/ac/za/cput/repository/student/StudentRepository.java
  src/main/java/ac/za/cput/service/IService.java
  src/main/java/ac/za/cput/service/employee/IEmployeeService.java
  src/main/java/ac/za/cput/service/employee/impl/EmployeeServiceImpl.java
  src/main/java/ac/za/cput/service/student/StudentService.java
  src/main/java/ac/za/cput/service/student/impl/StudentServiceImpl.java
  src/main/resources/application.properties
  src/test/java/ac/za/cput/factory/employee/EmployeeFactoryTest.java
  src/test/java/ac/za/cput/factory/student/StudentFactoryTest.java
  src/test/java/ac/za/cput/service/employee/impl/EmployeeServiceImplTest.java
  src/test/java/ac/za/cput/service/student/impl/StudentServiceImplTest.java
  target/classes/ac/za/cput/controller/employee/EmployeeController.class
  target/classes/ac/za/cput/controller/student/StudentController.class
  target/classes/ac/za/cput/domain/employee/Employee$Builder.class
  target/classes/ac/za/cput/domain/employee/Employee.class
  target/classes/ac/za/cput/domain/student/Student$Builder.class
  target/classes/ac/za/cput/domain/student/Student.class
  target/classes/ac/za/cput/repository/employee/EmployeeRepository.class
  target/classes/ac/za/cput/service/IService.class
  target/classes/ac/za/cput/service/employee/impl/EmployeeServiceImpl.class
  target/classes/ac/za/cput/service/student/impl/StudentServiceImpl.class
  target/classes/application.properties
  target/test-classes/ac/za/cput/service/employee/impl/EmployeeServiceImplTest.class
  target/test-classes/ac/za/cput/service/student/impl/StudentServiceImplTest.class
Labels: enhancement

#45 Country.Java and Readme
  README.md
  src/main/java/ac/za/cput/domain/country/Country.java
Labels: enhancement

#47 CountryFactory class and Test
  src/main/java/ac/za/cput/factory/country/CountryFactory.java
  src/test/java/ac/za/cput/factory/country/CountryFactoryTest.java
Labels: enhancement

#50 CountryRepository interface
  src/main/java/ac/za/cput/repository/country/CountryRepository.java
Labels: enhancement

#53 Name Entity
  src/main/java/ac/za/cput/domain/name/Name.java
Labels: enhancement

#52 Pull Request for Domain StudentAddress
  src/main/java/ac/za/cput/domain/StudentAddress/Address.java
  src/main/java/ac/za/cput/domain/StudentAddress/StudentAddress.java
  src/main/java/ac/za/cput/domain/studentAddress/Address.java
Labels: enhancement

#54 Name Factory created
  src/main/java/ac/za/cput/factory/name/NameFactory.java
Labels: good first issue

#55 Name Repository created
  src/main/java/ac/za/cput/repository/name/NameRepository.java
  src/test/java/ac/za/cput/factory/name/NameFactoryTest.java
  target/classes/ac/za/cput/controller/student/StudentController.class
  target/classes/ac/za/cput/domain/employee/Employee$Builder.class
  target/classes/ac/za/cput/domain/employee/Employee.class
  target/classes/ac/za/cput/domain/name/Name$Builder.class
  target/classes/ac/za/cput/domain/name/Name.class
  target/classes/ac/za/cput/domain/student/Student$Builder.class
  target/classes/ac/za/cput/domain/student/Student.class
  target/classes/ac/za/cput/factory/employee/EmployeeFactory.class
  target/classes/ac/za/cput/factory/name/NameFactory.class
  target/classes/ac/za/cput/factory/student/StudentFactory.class
  target/classes/ac/za/cput/repository/name/NameRepository.class
  target/classes/ac/za/cput/service/employee/impl/EmployeeServiceImpl.class
  target/classes/application.properties
  target/test-classes/ac/za/cput/factory/employee/EmployeeFactoryTest.class
  target/test-classes/ac/za/cput/factory/name/NameFactoryTest.class
  target/test-classes/ac/za/cput/factory/student/StudentFactoryTest.class
  target/test-classes/ac/za/cput/service/employee/impl/EmployeeServiceImplTest.class
  target/test-classes/ac/za/cput/service/student/impl/StudentServiceImplTest.class
Labels: enhancement

#56 Pull Request StudentAddress
  src/main/java/ac/za/cput/domain/studentAddress/Address.java
Labels: enhancement, good first issue

#57 Address class
  src/main/java/ac/za/cput/domain/address/Address.java
Labels: enhancement

#59 Service class for Name created
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  .idea/compiler.xml
  .idea/runConfigurations.xml
  src/main/java/ac/za/cput/service/name/NameService.java
  src/main/java/ac/za/cput/service/name/impl/NameServiceImpl.java
  src/test/java/ac/za/cput/service/name/impl/NameServiceImplTest.java
  target/classes/ac/za/cput/service/name/NameService.class
  target/classes/ac/za/cput/service/name/impl/NameServiceImpl.class
  target/test-classes/ac/za/cput/service/name/impl/NameServiceImplTest.class
Labels: good first issue

#60 Service implementation, interface and Test
  src/main/java/ac/za/cput/service/country/CountryService.java
  src/main/java/ac/za/cput/service/country/Impl/CountryServiceImpl.java
  src/test/java/ac/za/cput/service/country/impl/CountryServiceImplTest.java
Labels: good first issue

#63 Pull Request for Repository of StudentAddress
  src/main/java/ac/za/cput/repository/StudentAddress/StudentAddressRepository.java
Labels: enhancement

#64 Name Entity edited
  src/main/java/ac/za/cput/controller/student/StudentController.java
  src/main/java/ac/za/cput/domain/name/Name.java
  src/main/java/ac/za/cput/domain/student/Student.java
  src/main/java/ac/za/cput/factory/name/NameFactory.java
  src/main/java/ac/za/cput/factory/student/StudentFactory.java
  src/main/java/ac/za/cput/repository/name/NameRepository.java
  src/main/java/ac/za/cput/repository/student/StudentRepository.java
  src/main/java/ac/za/cput/service/name/NameService.java
  src/main/java/ac/za/cput/service/name/impl/NameServiceImpl.java
  src/main/java/ac/za/cput/service/student/StudentService.java
  src/main/java/ac/za/cput/service/student/impl/StudentServiceImpl.java
  src/main/resources/application.properties
  src/test/java/ac/za/cput/factory/name/NameFactoryTest.java
  src/test/java/ac/za/cput/factory/student/StudentFactoryTest.java
  src/test/java/ac/za/cput/service/name/impl/NameServiceImplTest.java
  src/test/java/ac/za/cput/service/student/impl/StudentServiceImplTest.java
  target/classes/ac/za/cput/controller/student/StudentController.class
  target/classes/ac/za/cput/domain/name/Name$Builder.class
  target/classes/ac/za/cput/domain/name/Name.class
  target/classes/ac/za/cput/domain/student/Student$Builder.class
  target/classes/ac/za/cput/domain/student/Student.class
  target/classes/ac/za/cput/factory/name/NameFactory.class
  target/classes/ac/za/cput/factory/student/StudentFactory.class
  target/classes/ac/za/cput/repository/name/NameRepository.class
  target/classes/ac/za/cput/service/name/NameService.class
  target/classes/ac/za/cput/service/name/impl/NameServiceImpl.class
  target/classes/ac/za/cput/service/student/impl/StudentServiceImpl.class
  target/classes/application.properties
  target/test-classes/ac/za/cput/factory/name/NameFactoryTest.class
  target/test-classes/ac/za/cput/factory/student/StudentFactoryTest.class
  target/test-classes/ac/za/cput/service/name/impl/NameServiceImplTest.class
Labels: enhancement

#69 Pull Request For Factory of StudentAddressFactoryTest
  src/test/java/ac/za/cput/factory/StudentAddress/StudentAddressFactoryTest.java
Labels: enhancement
